release: python manage.py migrate --noinput && python manage.py collectstatic --noinput
web: python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn core.wsgi --log-file -
