# Generated by Django 4.2.11 on 2026-06-05 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('coordinador', 'Coordinador'), ('cliente', 'Cliente')], default='cliente', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('email_verificado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('motor_diesel', 'Motor diesel'), ('electrico', 'Eléctrico'), ('frenos_suspension', 'Frenos y suspensión'), ('transmision', 'Transmisión'), ('hidraulico', 'Sistema hidráulico'), ('aire', 'Sistema de aire'), ('mecanica', 'Mecánica general'), ('soldadura', 'Soldadura')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('telefono', models.CharField(max_length=20)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('calificacion', models.FloatField(default=5.0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_verificacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('empresa', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('estatus', models.CharField(choices=[('proceso', 'En Proceso'), ('terminado', 'Terminado'), ('detenido', 'Detenido')], default='proceso', max_length=20)),
                ('unidad', models.CharField(max_length=200)),
                ('lugar', models.CharField(blank=True, max_length=200)),
                ('operador', models.CharField(blank=True, max_length=200)),
                ('reparacion', models.TextField(blank=True)),
                ('sal_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mo_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ref_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sal_ganancia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mo_ganancia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ref_ganancia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('factura', models.CharField(blank=True, max_length=50)),
                ('fecha_factura', models.DateField(blank=True, null=True)),
                ('estatus_factura', models.CharField(blank=True, choices=[('pagada', 'Pagada'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, limit_choices_to={'rol': 'cliente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_cliente', to=settings.AUTH_USER_MODEL)),
                ('coordinador', models.ForeignKey(blank=True, limit_choices_to={'rol__in': ['coordinador', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_coordinados', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tallerdiesel_api.proveedor')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('problema', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('atendida', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autor', models.CharField(max_length=100)),
                ('calificacion', models.IntegerField(default=5)),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to='tallerdiesel_api.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('tipo', models.CharField(default='solicitud', max_length=50)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_nombre', models.CharField(blank=True, max_length=200)),
                ('texto', models.TextField()),
                ('es_cambio_estatus', models.BooleanField(default=False)),
                ('estatus_anterior', models.CharField(blank=True, max_length=50)),
                ('estatus_nuevo', models.CharField(blank=True, max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tallerdiesel_api.ticket')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
