# Generated by Django 4.2.11 on 2026-07-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerdiesel_api', '0004_ticket_tipo_solicitud_tecnico_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenverificacion',
            name='codigo',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
