# Generated by Django 4.2.11 on 2026-07-23 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallerdiesel_api', '0005_tokenverificacion_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='tipo_unidad',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo_unidad',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('atendido', 'En camino'), ('proceso', 'Reparando'), ('terminado', 'Finalizado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='CodigoRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_recuperacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
