# Generated by Django 4.2.11 on 2026-07-23 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallerdiesel_api', '0006_solicitudservicio_tipo_unidad_ticket_tipo_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigorecuperacion',
            name='intentos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opinion',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opinion', to='tallerdiesel_api.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='alerta_sla_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tokenverificacion',
            name='intentos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UnidadFlotilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_unidad', models.CharField(blank=True, max_length=200)),
                ('unidad', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_flotilla', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['unidad'],
            },
        ),
    ]
